### ISSUE TITLE
Traduire la section "Abstract Factory et Builder"

### ISSUE THREAD

**Issue by DevAlves1993** [design-patterns-for-humans/French#4]
French : J'effectuerais la traduction de ces deux sections.
English : I would translate those two sections.

**Comment by g3r4n** [comment]
Thanks a lot for your contributions !

**Comment by DevAlves1993** [comment]
I started translating the two sections.
It would be judicious to create a label "in progress".

**Comment by DevAlves1993** [comment]
Both sections are completed.

**Comment by g3r4n** [comment]
#6 merged
